<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-19 11:20

$extensionPath = t3lib_extMgm::extPath('fluidpage');
return array(
	'tx_fluidpage_pi1' => $extensionPath . 'pi1/class.tx_fluidpage_pi1.php',
);
?>