<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-21 09:57

$extensionPath = t3lib_extMgm::extPath('fluidpage');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_fluidpage_controller_template' => $extensionClassesPath . 'Controller/Template.php',
	'tx_fluidpage_pi1' => $extensionClassesPath . 'Controller/tmp.php',
	'tx_fluidpage_model_template' => $extensionClassesPath . 'Model/Template.php',
	'tx_fluidpage_service_templatefactory' => $extensionClassesPath . 'Service/TemplateFactory.php',
);
?>
